apiVersion: skaffold/v1beta8
kind: Config
build:
  googleCloudBuild:
    projectId: dongdongchat
  artifacts:
  - image: gcr.io/dongdongchat/korean-dictionary-bot

deploy:
  kubectl:
    manifests:
      - k8s/*