apiVersion: skaffold/v1beta8
kind: Config
build:
  googleCloudBuild:
    projectId: jinjaio
  artifacts:
  - image: gcr.io/jinjaio/korean-dictionary-bot

deploy:
  kubectl:
    manifests:
      - k8s/*