apiVersion: apps/v1
kind: Deployment
metadata:
  name: korean-dictionary-bot-deployment
  labels:
    app: korean-dictionary-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  korean-dictionary-bot
  template:
    metadata:
      labels:
        app: korean-dictionary-bot
    spec:
      containers:
        - name: korean-dictionary-bot
          image: gcr.io/jinjaio/korean-dictionary-bot
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: production
          envFrom:
            - configMapRef:
                name: firebase
            - configMapRef:
                name: naver-api
            - configMapRef:
                name: youtube-api-key-3
            - configMapRef:
                name: korean-dictionary-bot
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "500Mi"
      hostNetwork: true